### ISSUE TITLE
error: project intelligence claims to be unable to download documentation (it did) and is unable to translate to any language

### ISSUE THREAD

**Issue by kohlth** [brandon3055/ProjectIntelligence#12] opened 2019-08-06 00:20 UTC
latest versions of all dependency's and draconic evolution and its dependencys 
latest version or draconic additions 
latest version of project intelligence 
(have checked as  of time of writing)
![image](https://user-images.githubusercontent.com/28970985/62502625-035f0300-b7b6-11e9-917d-bd66997e4d87.png)

**Comment by Gerkiz** [comment] 2019-08-06 17:43
Having the same issue.

**Comment by Syampuuh** [comment] 2019-08-07 05:31
+1. Redownloading/changing language does not make any difference.

**Comment by johnneijzen** [comment] 2019-08-07 07:35
+1 redownloading and changing language don't make a difference.

**Comment by johnneijzen** [comment] 2019-08-07 17:10
i think issue started when draconicevolution.json was updated

**Comment by mkienenb** [comment] 2019-08-07 20:59
Having the same issue for Project Ozone 3.

* PO3-3.0.41 
* Brandon's Core 1.12.2-2.4.12.205
* Project Intelligence 1.12.2-1.0.5.21
* Draconic evolution 1.12.2-2.3.22.343

It was working a few days ago but doesn't work today.

I spot-checked a few random urls in the modpack's config/brandon3055 config files, and they all seemed to be working.

@brandon3055  Is there anything extra that I can do to help debug the situation?   I do see that there is an updated Russian transaction in PI-Docs as of 4 days ago.

**Comment by Gerkiz** [comment] 2019-08-08 06:21
This should fix the issue.
Looks like someone forgot a `"` 😭 
[brandon3055/PI-Docs/pull/18]

**Comment by Bytegm** [comment] 2019-08-08 10:54
Извиняюсь, моя невнимательность виновата...

**Comment by Lithorn** [comment] 2019-08-08 14:25
I have this same issue with ProjectIntelligence-1.12.2-1.0.5.21-universal and Draconic. This is in Enigmatica 2 Expert, V1.66C

**Comment by Lithorn** [comment] 2019-08-08 15:16
I seem to have fixed mine by clicking EDIT, then navigating to the moddocs folder and getting the path url then pasting it in game. Also, I edited the RU language section with the commit fix listed in the pull. So far its working fine for me.

**Comment by Lithorn** [comment] 2019-08-08 15:44
I take back what I said, it worked ONCE and the moment I went to edit a spelling typo it crashed my client and continued to crash it afterwards. I had to delete the entire config folder to stop crashing, and trying to apply the fix I did before results in a crash about translation at line 125, net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Project Intelligence (projectintelligence)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 125 column 7 path $[24].translation  

This may be the missing " from the ru language section, so I added it and am testing it.

Seems to have worked. could be a fluke.

**Comment by GamingDennIz** [comment] 2019-08-12 05:09
I can't find a missing " in any file (either there is none or I'm blind) and I have the same issue.

**Comment by Gerkiz** [comment] 2019-08-12 08:21
Line 124 in file:
`ModDocs/draconicevolution/2.3.20/structure/lang/ru_ru.json`

**Comment by brandon3055** [comment] 2019-08-13 04:46
This should be fixed now. 
Thanks @Gerkiz

**Closed as completed by brandon3055** 2019-08-13 04:46 UTC
Labels: Fixed
