### ISSUE TITLE
Cannot open Draconic Evolution Tablet

### ISSUE THREAD

**Issue by Misha0909** [brandon3055/ProjectIntelligence#42] opened 2024-07-21 11:39 UTC
Mincraft - 1.12.2
Forge - 14.23.5.2860
Draconic Evolution - 2.3.28.354
Project intelligence-1.12.2-1.0.9.28
Java 8 Update 421

![350625671-82eb0eab-bea6-4976-91f6-f76cd6639962](https://github.com/user-attachments/assets/5fbe252c-225e-40d6-b71f-60c5c8c5c1c7)

**Comment by FoxMcloud5655** [comment] 2024-07-21 15:56
Duplicate of #41.

**Closed as not planned** 2024-07-21 17:04 UTC
