### ISSUE TITLE
Errors with styles

### ISSUE THREAD

**Issue by aaronhowser1** [brandon3055/ProjectIntelligence#11] opened 2019-06-22 06:29 UTC
Using ProjectIntelligence-1.12.2-1.0.5.21-universal

For some reason all my text is black, which really breaks the interface.

![image](https://user-images.githubusercontent.com/15698722/59960345-cef4e900-948c-11e9-9dc0-bb7ce84296ba.png)
![image](https://user-images.githubusercontent.com/15698722/59960335-b258b100-948c-11e9-8e24-ddcb61000745.png)

However, when I try to reload a Style, it tells me I've made changes to the current one and then throws an error (that I can't read because text is black)
![image](https://user-images.githubusercontent.com/15698722/59960356-08c5ef80-948d-11e9-9291-8069b5cb1c3e.png)
![image](https://user-images.githubusercontent.com/15698722/59960361-1aa79280-948d-11e9-9c11-9107809c3698.png)

**Comment by aaronhowser1** [comment] 2019-06-22 06:33
It was fixed by me deleting my brandon3055 folder, but I figure I should leave this open because that's more of a workaround than a fix

**Comment by aaronhowser1** [comment] 2019-06-22 06:50
Hmm I'm going through and re-downloading all the Draconic Evolution pages. It works fine until I get to the Chaos Guardian or Draconic Reactor, and then the text goes dark again and becomes hard to read. I can still safely change the styles, though.

**Comment by aaronhowser1** [comment] 2019-06-22 06:56
Re-deleted the config folder and went through and downloaded all the pages again, and the text went black just completely randomly this time. I wasn't even loading a new page. I have no idea what's going on tbh.

**Comment by brandon3055** [comment] 2019-06-29 04:30
Try reproducing this issue without your custom font mod.
Its very unlikely that this is a style error because i have seen a similar issue with another one of my mods. I suspect something is breaking text rendering. Rebooting you game to delete the config probably just fixed the issue temporarily.

**Comment by aaronhowser1** [comment] 2019-06-29 09:41
I uninstalled SmoothFont and went around the ui for a while and it never broke, so I guess that was the problem then. I'm not sure if the style error is related to that though, because I don't see how smoothfont would be changing the styles or preventing me from changing them.

**Comment by brandon3055** [comment] 2019-06-29 09:43
The issue is not the styles. I use a custom font renderer. I suspect SmoothFont is breaking my renderer somehow causing it to always render black.
I will look into it when i get a chance.

**Comment by aaronhowser1** [comment] 2019-06-29 09:45
But would SmoothFont also be causing the "One or more errors have occurred" thing when I try to change styles, like in the last image in the original post?

**Comment by brandon3055** [comment] 2019-06-29 10:23
Hmm... not sure. When that error window pops up it should also post something in the log. Can you show me what it posts?

**Comment by aaronhowser1** [comment] 2019-06-29 10:27
```
[05:27:06] [Client thread/ERROR] [brandonscore]: [Pi Reported Error]: Something went wrong while attempting to load the custom preset: G:\Games\MultiMC\instances\FTB Academy\.minecraft\config\brandon3055\ProjectIntelligence\GuiStyle\CustomPresets\vanilla.json (The system cannot find the file specified)
[05:27:06] [Client thread/ERROR] [projectintelligence]: Something went wrong while attempting to load the custom preset
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: java.io.FileNotFoundException: G:\Games\MultiMC\instances\FTB Academy\.minecraft\config\brandon3055\ProjectIntelligence\GuiStyle\CustomPresets\vanilla.json (The system cannot find the file specified)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at java.io.FileInputStream.open0(Native Method)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at java.io.FileInputStream.open(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at java.io.FileInputStream.<init>(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at java.io.FileReader.<init>(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.projectintelligence.client.StyleHandler.loadPreset(StyleHandler.java:511)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.projectintelligence.client.gui.guielements.GuiStyleEditor.lambda$null$15(GuiStyleEditor.java:186)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.brandonscore.client.gui.modulargui.baseelements.GuiButton.onPressed(GuiButton.java:460)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.brandonscore.client.gui.modulargui.baseelements.GuiButton.mouseClicked(GuiButton.java:437)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.mouseClicked(MGuiElementBase.java:588)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.brandonscore.client.gui.modulargui.baseelements.GuiPopUpDialogBase.mouseClicked(GuiPopUpDialogBase.java:76)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.brandonscore.client.gui.modulargui.GuiElementManager.mouseClicked(GuiElementManager.java:180)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.projectintelligence.client.gui.PIGuiContainer.mouseClicked(PIGuiContainer.java:251)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.projectintelligence.client.gui.GuiProjectIntelligence.func_73864_a(GuiProjectIntelligence.java:181)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at com.brandon3055.projectintelligence.client.gui.GuiProjectIntelligence.func_146274_d(GuiProjectIntelligence.java:229)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[05:27:06] [Client thread/INFO] [STDERR]: [com.brandon3055.projectintelligence.client.StyleHandler:loadPreset:527]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by brandon3055** [comment] 2019-06-29 10:29
Ok looks like a separate issue. I will look into that as well.

**Comment by brandon3055** [comment] 2019-07-02 13:02
This is turning out to be an absolute pain to debug. SmoothFont wont run in a dev environment and so far i have not been able to reproduce the issue in a test back. I will continue fiddling with this but i suggest you also report this issue to the SmoothFont devs.

btw can you please post your smoothfont config. (Including the selected font)

**Comment by aaronhowser1** [comment] 2019-07-02 16:09
[Here's my smoothfont.cfg](https://pastebin.com/FZwqQ7Sd)
```

    # Primary font name.
    # (The font installed in the system or existing in the externalFontPaths folders (default:<minecraft dir>/fontfiles).)
    S:fontName=Verdana

    # Secondary font name. It is used if the character cannot be rendered with the primary font.
    # (The font installed in the system or existing in the externalFontPaths folders (default:<minecraft dir>/fontfiles).)
    S:secondaryFontName=Arial Rounded MT Bold
```

**Comment by brandon3055** [comment] 2019-07-03 02:16
Ok not being able to reproduce this in dev is making things rather difficult but i have at least been able to figure out the exact trigger. Its a combination of smooth font and the blue slime from tinkers. 
When the mob soul on the DE page cycles to blue slime that's when it breaks. It also breaks if there happens to be a blue slime in the world.
This is 100% reproducible so i suggest you pass this info along to the smooth font devs.

**Comment by aaronhowser1** [comment] 2019-07-03 02:20
[Reported here](https://www.curseforge.com/minecraft/mc-mods/smooth-font/issues/18). 
Amazing that you've managed to find the exact trigger, especially when it's so obscure.

**Comment by FoxMcloud5655** [comment] 2019-07-03 02:21
Comes with being a developer :)

**Comment by brandon3055** [comment] 2019-07-03 02:22
Yea the giveaway was when i was just sitting there scratching my head trying to figure out why it wasn't happening then it suddenly just happened. The only thing changing on the screen was the mob soul.

**Comment by brandon3055** [comment] 2019-07-07 05:48
Looks like the SmoothFont dev has a fix for this in the works.

**Closed as completed by brandon3055** 2019-07-07 05:48 UTC
